# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQSxw3SiUPvmKUuEmgFp7bBi9hEx-y-s
"""

# Create box plots for each feature against wine quality
features = data.columns[:-1]
for feature in features:
    plt.figure(figsize=(8, 5))
    sns.boxplot(x='quality', y=feature, data=data)
    plt.xlabel('Wine Quality')
    plt.ylabel(feature)
    plt.title(f'{feature} vs. Wine Quality')
    plt.show()