# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQSxw3SiUPvmKUuEmgFp7bBi9hEx-y-s
"""



plt.figure(figsize=(8, 5))
sns.set(style="whitegrid")
sns.countplot(x='quality', data=data)
plt.xlabel('Wine Quality')
plt.ylabel('Count')
plt.title('Distribution of Wine Quality Scores')
plt.show()